baseURL = "http://spdldaemon.github.io/docs"
languageCode = "en-us"
title = "The SPDL Docs Repository"
theme = "learn"
GoogleAnalytics = "UA-71199601-2"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

# For FontAwesome in pages
[markup.goldmark.renderer]
unsafe = true

[params]
themeVariant = "stanford"

# Table of Contents
[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[[menu.shortcuts]]
name = "<i class='fas fa-archive'></i> The ME 218 Archive"
url = "https://me218archive.stanford.edu"
weight = 18

[[menu.shortcuts]] 
name = "<i class='fab fa-github'></i> Github Repository"
identifier = "ds"
url = "https://github.com/SPDLDaemon/spdl-docs-master"
weight = 19

[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> Hugo Documentation"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> Learn Theme Documentation"
identifier = "learndoc"
url = "https://learn.netlify.com/en/"
weight = 25
